# This workflow will build a Java project with Maven
name: Build and publish schemas with Maven

on:
  release:
    types: [ created ]

jobs:
  build-and-publish:
    name: Build and publish code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Clean with Maven
        run: mvn clean
      - name: Run publish with Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
            mvn --settings deploy-settings.xml deploy
