name: Zip and publish wsdl and schemas with Maven to Github packages

on:
  release:
    types: [ created ]

jobs:
  package-and-publish:
    name: Package and publish to Github packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Clean and package with Maven
        run: mvn clean package
      - name: Run publish with Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
            mvn --settings deploy-settings.xml deploy -Dfile=target/*.zip
