name: Zip and publish wsdl and schemas with Maven to Github packages

on:
  release:
    types: [ created ]

jobs:
  package-and-publish:
    name: Package and publish to Github packages
    runs-on: ubuntu-latest
    steps:
      # Check out main repository
      - name: Check out main repository
        uses: actions/checkout@v4

      # Clean and package with Maven
      - name: Clean and package with Maven
        run: mvn clean package

      # Publish artifacts to GitHub Packages with Maven
      - name: Run publish with Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings deploy-settings.xml deploy -Dfile=target/*.zip
