# Publish GitHub artifacts
name: Publish Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]  

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Step 1 - Create a temporary artifact temp folder
        run: mkdir -p temp
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cp -r ./src/ temp
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: ctr-schemas
          path: temp
